#Default port is 8761
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
     waitTimeInMsWhenSyncEmpty: 30
  serviceUrl:
   #  defaultZone: http://localhost:8761