version: '2'
services:
  eurekaserver:
    image: wfortini/tmx-eurekasvr:eurekasrv
    ports:
      - "8761:8761"
  configserver:
    image: wfortini/tmx-confsvr:springcloudconfig
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: wfortini/tmx-zuulsrv:zuulsrv
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      ORGSERVERNEW_PORT: "8087"
  database:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "licensedb"
  licensingservice:
    image: wfortini/tmx-licensing-service:springboot
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      AUTHSERVER_PORT:   "8091"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      KAFKASERVER_PORT: "2181"
      REDIS_PORT: "6379"
      ENCRYPT_KEY:       "IMSYMMETRIC"

  organizationservice:
    image: wfortini/tmx-organization-service:springboot
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice:8901/user"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      AUTHSERVER_PORT:   "8091"
      KAFKASERVER_PORT:    "2181"
      ENCRYPT_KEY: "IMSYMMETRIC"

  authenticationservice:
    image: wfortini/tmx-authentication-service:oauth2
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT: 5432
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY: "IMSYMMETRIC"

 redis:
  image: redis:alpine
  ports:
    - 6379:6379
 kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
  #orgservice-new:
  #  image: wfortini/tmx-orgservice-new:springboot
  #  ports:
  #    - "8087:8087"
  #  environment:
  #    PROFILE: "default"
  #    SERVER_PORT: "8087"
  #    CONFIGSERVER_URI: "http://configserver:8888"
  #    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  #    EUREKASERVER_PORT: "8761"
  #    DATABASESERVER_PORT: "5432"
  #    CONFIGSERVER_PORT: "8888"
  #    ENCRYPT_KEY: "IMSYMMETRIC"

 # specialroutes-service:
 #   image: wfortini/tmx-specialrouter-service:springboot
 #   ports:
 #     - "8910:8910"
 #   environment:
 #     PROFILE: "default"
 #     SERVER_PORT: "8910"
 #     CONFIGSERVER_URI: "http://configserver:8888"
 #     EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
 #     EUREKASERVER_PORT: "8761"
 #     DATABASESERVER_PORT: "5432"
 #     CONFIGSERVER_PORT: "8888"
 #     ENCRYPT_KEY: "IMSYMMETRIC"